Closes Issue20
SonicRift/Vestaboard pull request #21
Opened 2022-01-06 00:18 UTC by MiTo0o

- [x] #20 
- [x] Remove lines 54 / 55 in __init__.py where error checking/throwing for this error occurs, and replace with padding logic as above.
- [x] Add unit tests for padding logic to ensure all edge cases are accounted for

Concerns?:

- added .venv since a lot of people also use that to name their virtual envs, don't know if that's ok with you
- added warnings library (comes with python) to warn users instead of raising errors in some situations
- in the board.raw() function maybe have `len(charList)` in it's own varible? since it's used so much.

2022-01-06 15:33 UTC, SonicRift requested changes
This is excellent! 🎉 Nice job on the code and the tests! I've made a few suggestions for your consideration. Planning to add this in, and release a new version!

2022-01-06 15:33 UTC, SonicRift commented on vestaboard/__init__.py
> +      del charList[6:]
Normally I would advise against modifying the input array (side effects and all), but in this case I think it's a brilliant way around the fact that the `.raw()` function doesn't return anything - clever! 🧠

2022-01-06 15:33 UTC, SonicRift commented on tests/test_init.py
> +    assert small_board == expected
Let's add the blank padding lines here between tests for consistency - some of the lower ones have them, but not all.

2022-01-06 15:33 UTC, SonicRift commented on tests/test_init.py
> +    small_board = return_valid_small_board()
Let's also test that the right warning is being thrown on this and the next. You can use this context for that, it's similar to the assertion that an error will be thrown:
`with pytest.warns(UserWarning):`

2022-01-06 21:23 UTC, MiTo0o commented on tests/test_init.py
> +    vb.raw(small_board, pad='center')
didnt do it this way, maybe it's still ok?

2022-01-07 00:18 UTC, SonicRift approved these changes
Nice work on this, it looks great!

2022-01-07 00:18 UTC, merged